// <auto-generated />
using System;
using Last02.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Last02.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250811160404_add_seed_data")]
    partial class add_seed_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Last02.Data.Entities.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AudioType")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Audios");
                });

            modelBuilder.Entity("Last02.Data.Entities.Claims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Last02.Data.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 8, 11, 23, 4, 3, 743, DateTimeKind.Local).AddTicks(5887),
                            Deleted = false,
                            Title = "N5"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 8, 11, 23, 4, 3, 743, DateTimeKind.Local).AddTicks(6237),
                            Deleted = false,
                            Title = "N4"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 8, 11, 23, 4, 3, 743, DateTimeKind.Local).AddTicks(6240),
                            Deleted = false,
                            Title = "N3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 8, 11, 23, 4, 3, 743, DateTimeKind.Local).AddTicks(6241),
                            Deleted = false,
                            Title = "N2"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 8, 11, 23, 4, 3, 743, DateTimeKind.Local).AddTicks(6243),
                            Deleted = false,
                            Title = "N1"
                        });
                });

            modelBuilder.Entity("Last02.Data.Entities.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Example")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FlashcardCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Furigana")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meaning")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Flashcards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Example = "こんにちは、はじめまして。",
                            FlashcardCode = "N5-001-001",
                            Front = "こんにちは",
                            Furigana = "こんにちわ",
                            ImageUrl = "/images/flashcards/konnichiwa.jpg",
                            Meaning = "Xin chào",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 2,
                            Example = "おはよう、きょうもがんばってね。",
                            FlashcardCode = "N5-001-002",
                            Front = "おはよう",
                            Furigana = "おはよう",
                            ImageUrl = "/images/flashcards/ohayou.jpg",
                            Meaning = "Chào buổi sáng",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 3,
                            Example = "こんばんは、いい天気ですね。",
                            FlashcardCode = "N5-001-003",
                            Front = "こんばんは",
                            Furigana = "こんばんは",
                            ImageUrl = "/images/flashcards/konbanwa.jpg",
                            Meaning = "Chào buổi tối",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 4,
                            Example = "さようなら、またあした。",
                            FlashcardCode = "N5-001-004",
                            Front = "さようなら",
                            Furigana = "さようなら",
                            ImageUrl = "/images/flashcards/sayounara.jpg",
                            Meaning = "Tạm biệt",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 5,
                            Example = "プレゼントをありがとう。",
                            FlashcardCode = "N5-001-005",
                            Front = "ありがとう",
                            Furigana = "ありがとう",
                            ImageUrl = "/images/flashcards/arigatou.jpg",
                            Meaning = "Cảm ơn",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 6,
                            Example = "すみません、もういちどおねがいします。",
                            FlashcardCode = "N5-001-006",
                            Front = "すみません",
                            Furigana = "すみません",
                            ImageUrl = "/images/flashcards/sumimasen.jpg",
                            Meaning = "Xin lỗi / Làm phiền",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 7,
                            Example = "はい、わかりました。",
                            FlashcardCode = "N5-001-007",
                            Front = "はい",
                            Furigana = "はい",
                            ImageUrl = "/images/flashcards/hai.jpg",
                            Meaning = "Vâng / Đúng",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 8,
                            Example = "いいえ、ちがいます。",
                            FlashcardCode = "N5-001-008",
                            Front = "いいえ",
                            Furigana = "いいえ",
                            ImageUrl = "/images/flashcards/iie.jpg",
                            Meaning = "Không",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 9,
                            Example = "はじめまして、やまだです。",
                            FlashcardCode = "N5-001-009",
                            Front = "はじめまして",
                            Furigana = "はじめまして",
                            ImageUrl = "/images/flashcards/hajimemashite.jpg",
                            Meaning = "Rất vui được gặp bạn",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 10,
                            Example = "おやすみなさい、またあした。",
                            FlashcardCode = "N5-001-010",
                            Front = "おやすみなさい",
                            Furigana = "おやすみなさい",
                            ImageUrl = "/images/flashcards/oyasuminasai.jpg",
                            Meaning = "Chúc ngủ ngon",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 11,
                            Example = "りんごをいちつください。",
                            FlashcardCode = "N5-002-001",
                            Front = "いち",
                            Furigana = "いち",
                            ImageUrl = "/images/flashcards/ichi.jpg",
                            Meaning = "Số một",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 12,
                            Example = "にほんごをべんきょうしています。",
                            FlashcardCode = "N5-002-002",
                            Front = "に",
                            Furigana = "に",
                            ImageUrl = "/images/flashcards/ni.jpg",
                            Meaning = "Số hai",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 13,
                            Example = "さんにんのともだちがいます。",
                            FlashcardCode = "N5-002-003",
                            Front = "さん",
                            Furigana = "さん",
                            ImageUrl = "/images/flashcards/san.jpg",
                            Meaning = "Số ba",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 14,
                            Example = "よんじにあいましょう。",
                            FlashcardCode = "N5-002-004",
                            Front = "よん / し",
                            Furigana = "よん / し",
                            ImageUrl = "/images/flashcards/yon.jpg",
                            Meaning = "Số bốn",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 15,
                            Example = "ごじにおきます。",
                            FlashcardCode = "N5-002-005",
                            Front = "ご",
                            Furigana = "ご",
                            ImageUrl = "/images/flashcards/go.jpg",
                            Meaning = "Số năm",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 16,
                            Example = "ろっぷんまってください。",
                            FlashcardCode = "N5-002-006",
                            Front = "ろく",
                            Furigana = "ろく",
                            ImageUrl = "/images/flashcards/roku.jpg",
                            Meaning = "Số sáu",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 17,
                            Example = "ななじはんにおきます。",
                            FlashcardCode = "N5-002-007",
                            Front = "しち / なな",
                            Furigana = "しち / なな",
                            ImageUrl = "/images/flashcards/nana.jpg",
                            Meaning = "Số bảy",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 18,
                            Example = "はちじにでかけます。",
                            FlashcardCode = "N5-002-008",
                            Front = "はち",
                            Furigana = "はち",
                            ImageUrl = "/images/flashcards/hachi.jpg",
                            Meaning = "Số tám",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 19,
                            Example = "きゅうじまでにきてください。",
                            FlashcardCode = "N5-002-009",
                            Front = "きゅう / く",
                            Furigana = "きゅう / く",
                            ImageUrl = "/images/flashcards/kyuu.jpg",
                            Meaning = "Số chín",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 20,
                            Example = "じゅうにんのせいとがいます。",
                            FlashcardCode = "N5-002-010",
                            Front = "じゅう",
                            Furigana = "じゅう",
                            ImageUrl = "/images/flashcards/juu.jpg",
                            Meaning = "Số mười",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 21,
                            Example = "わたしのかぞくはごにんです。",
                            FlashcardCode = "N5-003-001",
                            Front = "かぞく",
                            Furigana = "かぞく",
                            ImageUrl = "/images/flashcards/kazoku.jpg",
                            Meaning = "Gia đình",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 22,
                            Example = "ちちはぎんこうではたらいています。",
                            FlashcardCode = "N5-003-002",
                            Front = "ちち",
                            Furigana = "ちち",
                            ImageUrl = "/images/flashcards/chichi.jpg",
                            Meaning = "Cha (nói về cha mình)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 23,
                            Example = "はははりょうりがじょうずです。",
                            FlashcardCode = "N5-003-003",
                            Front = "はは",
                            Furigana = "はは",
                            ImageUrl = "/images/flashcards/haha.jpg",
                            Meaning = "Mẹ (nói về mẹ mình)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 24,
                            Example = "おとうさんはどこですか。",
                            FlashcardCode = "N5-003-004",
                            Front = "おとうさん",
                            Furigana = "おとうさん",
                            ImageUrl = "/images/flashcards/otousan.jpg",
                            Meaning = "Bố (cách gọi lịch sự)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 25,
                            Example = "おかあさんはげんきですか。",
                            FlashcardCode = "N5-003-005",
                            Front = "おかあさん",
                            Furigana = "おかあさん",
                            ImageUrl = "/images/flashcards/okaasan.jpg",
                            Meaning = "Mẹ (cách gọi lịch sự)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 26,
                            Example = "あにはだいがくせいです。",
                            FlashcardCode = "N5-003-006",
                            Front = "あに",
                            Furigana = "あに",
                            ImageUrl = "/images/flashcards/ani.jpg",
                            Meaning = "Anh trai (nói về anh mình)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 27,
                            Example = "あねはせんせいです。",
                            FlashcardCode = "N5-003-007",
                            Front = "あね",
                            Furigana = "あね",
                            ImageUrl = "/images/flashcards/ane.jpg",
                            Meaning = "Chị gái (nói về chị mình)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 28,
                            Example = "おにいさんはなんさいですか。",
                            FlashcardCode = "N5-003-008",
                            Front = "おにいさん",
                            Furigana = "おにいさん",
                            ImageUrl = "/images/flashcards/oniisan.jpg",
                            Meaning = "Anh trai (lịch sự)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 29,
                            Example = "おねえさんはべんきょうしていますか。",
                            FlashcardCode = "N5-003-009",
                            Front = "おねえさん",
                            Furigana = "おねえさん",
                            ImageUrl = "/images/flashcards/oneesan.jpg",
                            Meaning = "Chị gái (lịch sự)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 30,
                            Example = "きょうだいはなんにんいますか。",
                            FlashcardCode = "N5-003-010",
                            Front = "きょうだい",
                            Furigana = "きょうだい",
                            ImageUrl = "/images/flashcards/kyoudai.jpg",
                            Meaning = "Anh chị em",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 31,
                            Example = "がっこうへいきます。",
                            FlashcardCode = "N5-004-001",
                            Front = "がっこう",
                            Furigana = "がっこう",
                            ImageUrl = "/images/flashcards/gakkou.jpg",
                            Meaning = "Trường học",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 32,
                            Example = "せんせいはにほんじんです。",
                            FlashcardCode = "N5-004-002",
                            Front = "せんせい",
                            Furigana = "せんせい",
                            ImageUrl = "/images/flashcards/sensei.jpg",
                            Meaning = "Giáo viên",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 33,
                            Example = "わたしはがくせいです。",
                            FlashcardCode = "N5-004-003",
                            Front = "がくせい",
                            Furigana = "がくせい",
                            ImageUrl = "/images/flashcards/gakusei.jpg",
                            Meaning = "Học sinh / Sinh viên",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 34,
                            Example = "きょうしつはにかいにあります。",
                            FlashcardCode = "N5-004-004",
                            Front = "きょうしつ",
                            Furigana = "きょうしつ",
                            ImageUrl = "/images/flashcards/kyoushitsu.jpg",
                            Meaning = "Phòng học",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 35,
                            Example = "ほんをよみます。",
                            FlashcardCode = "N5-004-005",
                            Front = "ほん",
                            Furigana = "ほん",
                            ImageUrl = "/images/flashcards/hon.jpg",
                            Meaning = "Sách",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 36,
                            Example = "えんぴつでかきます。",
                            FlashcardCode = "N5-004-006",
                            Front = "えんぴつ",
                            Furigana = "えんぴつ",
                            ImageUrl = "/images/flashcards/enpitsu.jpg",
                            Meaning = "Bút chì",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 37,
                            Example = "じしょをつかいます。",
                            FlashcardCode = "N5-004-007",
                            Front = "じしょ",
                            Furigana = "じしょ",
                            ImageUrl = "/images/flashcards/jisho.jpg",
                            Meaning = "Từ điển",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 38,
                            Example = "らいしゅうしけんがあります。",
                            FlashcardCode = "N5-004-008",
                            Front = "しけん",
                            Furigana = "しけん",
                            ImageUrl = "/images/flashcards/shiken.jpg",
                            Meaning = "Kỳ thi",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 39,
                            Example = "まいにちべんきょうします。",
                            FlashcardCode = "N5-004-009",
                            Front = "べんきょう",
                            Furigana = "べんきょう",
                            ImageUrl = "/images/flashcards/benkyou.jpg",
                            Meaning = "Học tập",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 40,
                            Example = "やすみじかんにともだちとあそびます。",
                            FlashcardCode = "N5-004-010",
                            Front = "やすみじかん",
                            Furigana = "やすみじかん",
                            ImageUrl = "/images/flashcards/yasumijikan.jpg",
                            Meaning = "Giờ nghỉ",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 41,
                            Example = "みせでくだものをかいます。",
                            FlashcardCode = "N5-005-001",
                            Front = "みせ",
                            Furigana = "みせ",
                            ImageUrl = "/images/flashcards/mise.jpg",
                            Meaning = "Cửa hàng",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 42,
                            Example = "かいものにいきます。",
                            FlashcardCode = "N5-005-002",
                            Front = "かいもの",
                            Furigana = "かいもの",
                            ImageUrl = "/images/flashcards/kaimono.jpg",
                            Meaning = "Mua sắm",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 43,
                            Example = "ほんをかいました。",
                            FlashcardCode = "N5-005-003",
                            Front = "かう",
                            Furigana = "かう",
                            ImageUrl = "/images/flashcards/kau.jpg",
                            Meaning = "Mua",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 44,
                            Example = "このみせはやさいをうっています。",
                            FlashcardCode = "N5-005-004",
                            Front = "うる",
                            Furigana = "うる",
                            ImageUrl = "/images/flashcards/uru.jpg",
                            Meaning = "Bán",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 45,
                            Example = "このシャツはやすいです。",
                            FlashcardCode = "N5-005-005",
                            Front = "やすい",
                            Furigana = "やすい",
                            ImageUrl = "/images/flashcards/yasui.jpg",
                            Meaning = "Rẻ",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 46,
                            Example = "このくつはたかいです。",
                            FlashcardCode = "N5-005-006",
                            Front = "たかい",
                            Furigana = "たかい",
                            ImageUrl = "/images/flashcards/takai.jpg",
                            Meaning = "Đắt / Cao",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 47,
                            Example = "あたらしいかばんをかいました。",
                            FlashcardCode = "N5-005-007",
                            Front = "かばん",
                            Furigana = "かばん",
                            ImageUrl = "/images/flashcards/kaban.jpg",
                            Meaning = "Cặp sách / Túi",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 48,
                            Example = "さいふをなくしました。",
                            FlashcardCode = "N5-005-008",
                            Front = "さいふ",
                            Furigana = "さいふ",
                            ImageUrl = "/images/flashcards/saifu.jpg",
                            Meaning = "Ví tiền",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 49,
                            Example = "シャツをきます。",
                            FlashcardCode = "N5-005-009",
                            Front = "きる",
                            Furigana = "きる",
                            ImageUrl = "/images/flashcards/kiru.jpg",
                            Meaning = "Mặc (quần áo)",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 50,
                            Example = "くつをはきます。",
                            FlashcardCode = "N5-005-010",
                            Front = "はく",
                            Furigana = "はく",
                            ImageUrl = "/images/flashcards/haku.jpg",
                            Meaning = "Mang (giày, quần)",
                            TopicId = 5
                        });
                });

            modelBuilder.Entity("Last02.Data.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Last02.Data.Entities.LocalizedMessage", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Code", "LanguageCode");

                    b.ToTable("LocalizedMessages");
                });

            modelBuilder.Entity("Last02.Data.Entities.MemberCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("Progress")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberCourses");
                });

            modelBuilder.Entity("Last02.Data.Entities.MemberFlashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlashcardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RememberCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberFlashcards");
                });

            modelBuilder.Entity("Last02.Data.Entities.Members", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MemberLastActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimesIsLogoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Last02.Data.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HexColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TopicCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Description = "Học các câu chào hỏi và giao tiếp cơ bản trong tiếng Nhật N5.",
                            HexColorCode = "#FFB74D",
                            IsFree = true,
                            Title = "Chào hỏi cơ bản",
                            TopicCode = "N5-001"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Description = "Học cách đếm số, nói giờ, ngày tháng trong tiếng Nhật N5.",
                            HexColorCode = "#4DB6AC",
                            IsFree = true,
                            Title = "Số đếm & Thời gian",
                            TopicCode = "N5-002"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            Description = "Từ vựng và mẫu câu liên quan đến gia đình trong tiếng Nhật N5.",
                            HexColorCode = "#64B5F6",
                            IsFree = false,
                            Title = "Gia đình",
                            TopicCode = "N5-003"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            Description = "Từ vựng và mẫu câu sử dụng trong môi trường học tập.",
                            HexColorCode = "#BA68C8",
                            IsFree = false,
                            Title = "Trường học",
                            TopicCode = "N5-004"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 1,
                            Description = "Từ vựng và mẫu câu giao tiếp khi đi mua sắm.",
                            HexColorCode = "#E57373",
                            IsFree = false,
                            Title = "Mua sắm",
                            TopicCode = "N5-005"
                        });
                });

            modelBuilder.Entity("Last02.Data.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastForgotPasswordRequestAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialProviderToken")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TemporaryPasswordExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("TemporaryPasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Last02.Data.Entities.Audio", b =>
                {
                    b.HasOne("Last02.Data.Entities.Course", "Course")
                        .WithMany("Audios")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Last02.Data.Entities.Flashcard", b =>
                {
                    b.HasOne("Last02.Data.Entities.Topic", "Topic")
                        .WithMany("Flashcards")
                        .HasForeignKey("TopicId");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Last02.Data.Entities.MemberCourse", b =>
                {
                    b.HasOne("Last02.Data.Entities.Course", "Course")
                        .WithMany("MemberCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Last02.Data.Entities.Members", "Member")
                        .WithMany("MemberCourses")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Last02.Data.Entities.MemberFlashcard", b =>
                {
                    b.HasOne("Last02.Data.Entities.Flashcard", "Flashcard")
                        .WithMany()
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Last02.Data.Entities.Members", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Last02.Data.Entities.Members", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Last02.Data.Entities.Users", "User")
                        .WithOne("Member")
                        .HasForeignKey("Last02.Data.Entities.Members", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Last02.Data.Entities.Topic", b =>
                {
                    b.HasOne("Last02.Data.Entities.Course", "Course")
                        .WithMany("Topics")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Last02.Data.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Last02.Data.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Last02.Data.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Last02.Data.Entities.Users", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UsersId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Last02.Data.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Last02.Data.Entities.Course", b =>
                {
                    b.Navigation("Audios");

                    b.Navigation("MemberCourses");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Last02.Data.Entities.Members", b =>
                {
                    b.Navigation("MemberCourses");
                });

            modelBuilder.Entity("Last02.Data.Entities.Topic", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("Last02.Data.Entities.Users", b =>
                {
                    b.Navigation("Member");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
