// <auto-generated />
using System;
using Last02.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Last02.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Last02.Data.Entities.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AudioType")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<string>("Script")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScriptEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScriptVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Audios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AudioCode = "A001",
                            AudioType = 1,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\sample1.mp3",
                            IsFree = true,
                            Script = "おはようございます。今日はとてもいい天気ですね。朝ごはんはもう食べましたか。私はパンとコーヒーをいただきました。これから学校へ行く予定です。",
                            ScriptEn = "Good morning. The weather is really nice today. Have you had breakfast yet? I had bread and coffee. I’m planning to go to school now.",
                            ScriptVi = "Chào buổi sáng. Hôm nay trời rất đẹp. Bạn đã ăn sáng chưa? Tôi vừa ăn bánh mì và uống cà phê. Sắp tới tôi sẽ đi đến trường.",
                            Section = "Chapter 1",
                            SortOrder = 1,
                            Title = "Sample 1"
                        },
                        new
                        {
                            Id = 2,
                            AudioCode = "A002",
                            AudioType = 1,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\sample2.mp3",
                            IsFree = true,
                            Script = "こんにちは。今日は授業が早く終わりました。午後は友達と図書館で勉強します。終わったら一緒にカフェに行く予定です。あなたも来ませんか。",
                            ScriptEn = "Hello. Today’s class finished early. In the afternoon I’ll study at the library with friends. After that we plan to go to a café. Would you like to come too?",
                            ScriptVi = "Xin chào. Hôm nay buổi học kết thúc sớm. Buổi chiều tôi sẽ học ở thư viện với bạn bè. Sau khi xong chúng tôi sẽ đi quán cà phê. Bạn có muốn đi cùng không?",
                            Section = "Chapter 1",
                            SortOrder = 2,
                            Title = "Sample 2"
                        },
                        new
                        {
                            Id = 3,
                            AudioCode = "A003",
                            AudioType = 1,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\sample3.mp3",
                            IsFree = false,
                            Script = "こんばんは。今日は本当に忙しい一日でした。たくさんの会議に参加して疲れました。でも同僚たちと楽しく話せて良かったです。これからお風呂に入って早く寝ます。",
                            ScriptEn = "Good evening. Today was really busy. I joined many meetings and got tired. But I enjoyed talking with my colleagues. Now I’ll take a bath and sleep early.",
                            ScriptVi = "Chào buổi tối. Hôm nay thật sự là một ngày bận rộn. Tôi tham dự rất nhiều cuộc họp nên khá mệt. Nhưng tôi đã trò chuyện vui vẻ với đồng nghiệp, điều đó thật tuyệt. Giờ tôi sẽ tắm và ngủ sớm.",
                            Section = "Chapter 1",
                            SortOrder = 3,
                            Title = "Sample 3"
                        },
                        new
                        {
                            Id = 4,
                            AudioCode = "A004",
                            AudioType = 1,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\sample4.mp3",
                            IsFree = false,
                            Script = "ありがとうございます。あなたの助けがなければ終わらなかったでしょう。おかげで時間通りに提出できました。次回は私が手伝います。これからもよろしくお願いします。",
                            ScriptEn = "Thank you very much. Without you I couldn’t have finished. Thanks to you I submitted on time. Next time I will help you. I look forward to working together again.",
                            ScriptVi = "Cảm ơn bạn rất nhiều. Nếu không có bạn tôi đã không hoàn thành. Nhờ bạn mà tôi kịp nộp đúng giờ. Lần tới tôi sẽ giúp bạn. Mong được hợp tác tiếp.",
                            Section = "Chapter 2",
                            SortOrder = 4,
                            Title = "Sample 4"
                        },
                        new
                        {
                            Id = 5,
                            AudioCode = "A005",
                            AudioType = 1,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\sample5.mp3",
                            IsFree = true,
                            Script = "すみません、道に迷いました。駅までの行き方を教えていただけますか。地図を持っていますが少し分かりにくいです。バスと電車どちらが早いでしょうか。助けてくださってありがとうございます。",
                            ScriptEn = "Excuse me, I’m lost. Could you tell me how to get to the station? I have a map but it’s a bit confusing. Which is faster, bus or train? Thank you for helping me.",
                            ScriptVi = "Xin lỗi, tôi bị lạc đường. Bạn có thể chỉ giúp tôi đường đến ga tàu không? Tôi có bản đồ nhưng hơi khó hiểu. Đi xe buýt hay tàu sẽ nhanh hơn? Cảm ơn bạn đã giúp đỡ.",
                            Section = "Chapter 2",
                            SortOrder = 5,
                            Title = "Sample 5"
                        },
                        new
                        {
                            Id = 6,
                            AudioCode = "A006",
                            AudioType = 1,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\sample6.mp3",
                            IsFree = false,
                            Script = "初めまして。私は田中と申します。東京から来ました。日本語を勉強して三年になります。これから一緒に楽しく学びたいと思います。どうぞよろしくお願いします。",
                            ScriptEn = "Nice to meet you. My name is Tanaka and I’m from Tokyo. I’ve been studying Japanese for three years. I hope to enjoy learning together with you. Please take care of me.",
                            ScriptVi = "Rất vui được gặp bạn. Tôi tên là Tanaka và đến từ Tokyo. Tôi đã học tiếng Nhật được ba năm. Tôi mong muốn cùng bạn học tập vui vẻ từ bây giờ. Rất mong được giúp đỡ.",
                            Section = "Chapter 2",
                            SortOrder = 6,
                            Title = "Sample 6"
                        },
                        new
                        {
                            Id = 7,
                            AudioCode = "A007",
                            AudioType = 1,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\sample7.mp3",
                            IsFree = true,
                            Script = "昨日は雨が降りましたが、今日は晴れてとても気持ちがいいです。朝から公園を散歩しました。花がたくさん咲いていました。鳥の声も聞こえてとても楽しかったです。写真もたくさん撮りました。",
                            ScriptEn = "It rained yesterday, but today it’s sunny and very pleasant. I took a walk in the park this morning. Many flowers were blooming. I heard birds singing and enjoyed it. I also took many photos.",
                            ScriptVi = "Hôm qua trời mưa nhưng hôm nay trời nắng thật dễ chịu. Sáng nay tôi đi dạo trong công viên. Có rất nhiều hoa nở. Tiếng chim hót nghe rất vui. Tôi cũng chụp nhiều bức ảnh.",
                            Section = "Chapter 3",
                            SortOrder = 7,
                            Title = "Sample 7"
                        },
                        new
                        {
                            Id = 8,
                            AudioCode = "A008",
                            AudioType = 1,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\sample8.mp3",
                            IsFree = false,
                            Script = "明日は友達と一緒に映画を見に行く予定です。とても楽しみにしています。映画の後はレストランで夕食を食べます。新しいメニューがあるそうです。写真も撮ってSNSにアップしたいです。",
                            ScriptEn = "Tomorrow I plan to watch a movie with friends. I’m really looking forward to it. After the movie we’ll have dinner at a restaurant. I heard there’s a new menu. I want to take photos and post them online.",
                            ScriptVi = "Ngày mai tôi dự định đi xem phim cùng bạn. Tôi rất mong chờ. Sau khi xem phim, chúng tôi sẽ ăn tối ở nhà hàng. Nghe nói có thực đơn mới. Tôi cũng muốn chụp ảnh và đăng lên mạng xã hội.",
                            Section = "Chapter 3",
                            SortOrder = 8,
                            Title = "Sample 8"
                        },
                        new
                        {
                            Id = 9,
                            AudioCode = "A009",
                            AudioType = 1,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\sample9.mp3",
                            IsFree = true,
                            Script = "このレストランの料理はとても美味しいです。特にラーメンがおすすめです。スープが濃くて香りが良いです。デザートのケーキも絶品でした。友達にもぜひ紹介したいです。",
                            ScriptEn = "The food at this restaurant is very delicious, especially the ramen. The broth is rich and fragrant. The dessert cake was excellent too. I definitely want to recommend it to my friends.",
                            ScriptVi = "Món ăn ở nhà hàng này rất ngon, đặc biệt là mì ramen. Nước dùng đậm đà và thơm. Bánh ngọt tráng miệng cũng tuyệt vời. Tôi nhất định sẽ giới thiệu cho bạn bè.",
                            Section = "Chapter 3",
                            SortOrder = 9,
                            Title = "Sample 9"
                        },
                        new
                        {
                            Id = 10,
                            AudioCode = "A010",
                            AudioType = 1,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\sample10.mp3",
                            IsFree = false,
                            Script = "日本へ行ったら、ぜひ京都を訪れてください。美しい寺や神社がたくさんあります。四季折々の景色が楽しめます。歴史的な町並みも魅力的です。ゆっくり散歩すると心が落ち着きます。",
                            ScriptEn = "If you visit Japan, be sure to go to Kyoto. There are many beautiful temples and shrines. You can enjoy the scenery of all four seasons. The historical streets are charming. A slow walk there will calm your heart.",
                            ScriptVi = "Nếu bạn đến Nhật, hãy ghé thăm Kyoto. Nơi đây có rất nhiều đền chùa xinh đẹp. Bạn có thể thưởng thức phong cảnh bốn mùa. Phố cổ mang đậm dấu ấn lịch sử cũng rất hấp dẫn. Dạo bộ chậm rãi khiến tâm hồn bình yên.",
                            Section = "Chapter 4",
                            SortOrder = 10,
                            Title = "Sample 10"
                        },
                        new
                        {
                            Id = 21,
                            AudioCode = "G001",
                            AudioType = 0,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\grammar1.mp3",
                            IsFree = true,
                            Script = "田中さんは音楽を聞きながら勉強します。勉強してから友達と公園へ行きます。公園で写真を撮ったことがありますか。私は一度も撮ったことがありません。でも、今日は写真を撮りたいです。",
                            ScriptEn = "Tanaka studies while listening to music. After studying, he goes to the park with friends. Have you ever taken pictures in the park? I never have. But today I want to take some photos.",
                            ScriptVi = "Anh Tanaka vừa nghe nhạc vừa học. Sau khi học xong anh ấy đi công viên với bạn. Bạn đã từng chụp ảnh ở công viên chưa? Tôi thì chưa từng. Nhưng hôm nay tôi muốn chụp ảnh.",
                            Section = "Grammar N5 - 1",
                            SortOrder = 1,
                            Title = "Grammar Sample 1"
                        },
                        new
                        {
                            Id = 22,
                            AudioCode = "G002",
                            AudioType = 0,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\grammar2.mp3",
                            IsFree = false,
                            Script = "朝ごはんを食べてから会社へ行きます。会社に着いたらまずメールをチェックします。会議が終わった後、上司と話さなければなりません。午後はお客様に電話をかけたいです。でも忙しいかもしれません。",
                            ScriptEn = "I go to the office after eating breakfast. Upon arrival, I first check emails. After the meeting, I must talk with my boss. In the afternoon I’d like to call customers, but I might be busy.",
                            ScriptVi = "Sau khi ăn sáng tôi đi làm. Đến công ty tôi kiểm tra email trước. Sau khi họp xong, tôi phải nói chuyện với sếp. Buổi chiều tôi muốn gọi điện cho khách hàng nhưng có thể sẽ bận.",
                            Section = "Grammar N5 - 1",
                            SortOrder = 2,
                            Title = "Grammar Sample 2"
                        },
                        new
                        {
                            Id = 23,
                            AudioCode = "G003",
                            AudioType = 0,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\grammar3.mp3",
                            IsFree = true,
                            Script = "昨日は雨が降っていましたが、今日は晴れそうです。散歩したいけれど、仕事をしなければなりません。仕事が終わったら一緒に映画を見に行きませんか。映画を見たことがありますか。",
                            ScriptEn = "It rained yesterday, but it looks sunny today. I want to take a walk, but I must work. After finishing work, shall we go to watch a movie? Have you seen that movie before?",
                            ScriptVi = "Hôm qua trời mưa nhưng hôm nay có vẻ nắng. Tôi muốn đi dạo nhưng phải làm việc. Sau khi làm xong chúng ta đi xem phim nhé. Bạn đã từng xem phim đó chưa?",
                            Section = "Grammar N5 - 2",
                            SortOrder = 3,
                            Title = "Grammar Sample 3"
                        },
                        new
                        {
                            Id = 24,
                            AudioCode = "G004",
                            AudioType = 0,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\grammar4.mp3",
                            IsFree = false,
                            Script = "母は料理を作りながら歌を歌っています。私は宿題を終えてから手伝います。夜ご飯を食べたあと、みんなでテレビを見ます。楽しい時間を過ごしたいです。",
                            ScriptEn = "Mother sings while cooking. After finishing homework, I will help her. After dinner, we all watch TV together. I want to spend a fun time.",
                            ScriptVi = "Mẹ vừa nấu ăn vừa hát. Tôi làm xong bài tập rồi sẽ giúp mẹ. Sau khi ăn tối, cả nhà cùng xem TV. Tôi muốn có thời gian vui vẻ.",
                            Section = "Grammar N5 - 2",
                            SortOrder = 4,
                            Title = "Grammar Sample 4"
                        },
                        new
                        {
                            Id = 25,
                            AudioCode = "G005",
                            AudioType = 0,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\grammar5.mp3",
                            IsFree = true,
                            Script = "駅に着いたら田中さんに電話します。田中さんはもう駅に来たことがありますか。来なければなりませんが、少し遅れるかもしれません。私は本を読みながら待っています。",
                            ScriptEn = "I will call Tanaka when I arrive at the station. Has he been to this station before? He must come, but he might be late. I’ll wait while reading a book.",
                            ScriptVi = "Khi đến ga tôi sẽ gọi cho Tanaka. Tanaka đã từng đến ga này chưa? Anh ấy phải đến nhưng có thể sẽ trễ. Tôi sẽ vừa đọc sách vừa chờ.",
                            Section = "Grammar N5 - 3",
                            SortOrder = 5,
                            Title = "Grammar Sample 5"
                        },
                        new
                        {
                            Id = 26,
                            AudioCode = "G006",
                            AudioType = 0,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\grammar6.mp3",
                            IsFree = false,
                            Script = "週末は友達と買い物をしたいです。買い物してからカフェで休みます。コーヒーを飲みながら話すのが好きです。帰る前に駅でお土産を買わなければなりません。",
                            ScriptEn = "I want to shop with friends on the weekend. After shopping, we will rest at a café. I like talking while drinking coffee. Before going home, I must buy souvenirs at the station.",
                            ScriptVi = "Cuối tuần tôi muốn đi mua sắm với bạn. Sau khi mua sắm chúng tôi sẽ nghỉ ở quán cà phê. Tôi thích vừa uống cà phê vừa trò chuyện. Trước khi về phải mua quà lưu niệm ở ga.",
                            Section = "Grammar N5 - 3",
                            SortOrder = 6,
                            Title = "Grammar Sample 6"
                        },
                        new
                        {
                            Id = 27,
                            AudioCode = "G007",
                            AudioType = 0,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\grammar7.mp3",
                            IsFree = true,
                            Script = "朝ジョギングをしてから朝ごはんを食べます。走りながら音楽を聞くのが楽しいです。その後、学校へ行かなければなりません。授業が終わったあと、図書館で勉強したいです。",
                            ScriptEn = "I jog in the morning and then eat breakfast. Listening to music while running is fun. After that I must go to school. After class, I want to study at the library.",
                            ScriptVi = "Buổi sáng tôi chạy bộ rồi ăn sáng. Nghe nhạc khi chạy rất vui. Sau đó tôi phải đến trường. Sau giờ học tôi muốn học thêm ở thư viện.",
                            Section = "Grammar N5 - 4",
                            SortOrder = 7,
                            Title = "Grammar Sample 7"
                        },
                        new
                        {
                            Id = 28,
                            AudioCode = "G008",
                            AudioType = 0,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\grammar8.mp3",
                            IsFree = false,
                            Script = "友達は旅行したことがありますか。私は一度も海外へ行ったことがありません。でも、来年は行きたいです。パスポートを取らなければなりません。",
                            ScriptEn = "Has my friend ever traveled? I have never been abroad. But next year I want to go. I must get a passport.",
                            ScriptVi = "Bạn tôi đã từng đi du lịch chưa? Tôi chưa từng ra nước ngoài. Nhưng năm sau tôi muốn đi. Tôi phải làm hộ chiếu.",
                            Section = "Grammar N5 - 4",
                            SortOrder = 8,
                            Title = "Grammar Sample 8"
                        },
                        new
                        {
                            Id = 29,
                            AudioCode = "G009",
                            AudioType = 0,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\grammar9.mp3",
                            IsFree = true,
                            Script = "授業が始まる前に教室を掃除します。掃除しながら友達と話します。終わってからみんなで朝ごはんを食べに行きます。食べた後は図書館に行きたいです。",
                            ScriptEn = "Before class starts we clean the room. We talk while cleaning. After finishing we all go for breakfast. After eating I want to go to the library.",
                            ScriptVi = "Trước khi giờ học bắt đầu chúng tôi dọn lớp. Vừa dọn vừa trò chuyện. Dọn xong mọi người cùng đi ăn sáng. Ăn xong tôi muốn đến thư viện.",
                            Section = "Grammar N5 - 5",
                            SortOrder = 9,
                            Title = "Grammar Sample 9"
                        },
                        new
                        {
                            Id = 30,
                            AudioCode = "G010",
                            AudioType = 0,
                            CourseId = 1,
                            FileUrl = "E:\\Tốt nghiệp\\Thực tập tốt nghiệp\\audio\\grammar10.mp3",
                            IsFree = false,
                            Script = "昨日スーパーで買い物してから映画を見ました。映画を見ながらポップコーンを食べました。とても楽しかったです。帰る前に駅で友達に会わなければなりませんでした。",
                            ScriptEn = "Yesterday I went shopping at the supermarket and then watched a movie. I ate popcorn while watching. It was very fun. Before going home, I had to meet a friend at the station.",
                            ScriptVi = "Hôm qua tôi đi siêu thị mua sắm rồi xem phim. Vừa xem phim vừa ăn bỏng ngô. Rất vui. Trước khi về tôi phải gặp bạn ở ga.",
                            Section = "Grammar N5 - 5",
                            SortOrder = 10,
                            Title = "Grammar Sample 10"
                        });
                });

            modelBuilder.Entity("Last02.Data.Entities.Claims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Last02.Data.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 18, 11, 46, 32, 543, DateTimeKind.Local).AddTicks(2579),
                            Deleted = false,
                            Title = "N5"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 18, 11, 46, 32, 543, DateTimeKind.Local).AddTicks(2926),
                            Deleted = false,
                            Title = "N4"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 9, 18, 11, 46, 32, 543, DateTimeKind.Local).AddTicks(2928),
                            Deleted = false,
                            Title = "N3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 9, 18, 11, 46, 32, 543, DateTimeKind.Local).AddTicks(2929),
                            Deleted = false,
                            Title = "N2"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 9, 18, 11, 46, 32, 543, DateTimeKind.Local).AddTicks(2931),
                            Deleted = false,
                            Title = "N1"
                        });
                });

            modelBuilder.Entity("Last02.Data.Entities.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Example")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExampleEn")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExampleVi")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FlashcardCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Furigana")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeaningEn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MeaningVi")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Flashcards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Example = "こんにちは、はじめまして。",
                            ExampleEn = "Hello, nice to meet you.",
                            ExampleVi = "Xin chào, rất vui được gặp bạn.",
                            FlashcardCode = "N5-001-001",
                            Front = "こんにちは",
                            Furigana = "こんにちわ",
                            ImageUrl = "/images/flashcards/konnichiwa.jpg",
                            MeaningEn = "Hello",
                            MeaningVi = "Xin chào",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 2,
                            Example = "おはよう、きょうもがんばってね。",
                            ExampleEn = "Good morning, do your best today too.",
                            ExampleVi = "Chào buổi sáng, hôm nay cùng cố gắng nhé.",
                            FlashcardCode = "N5-001-002",
                            Front = "おはよう",
                            Furigana = "おはよう",
                            ImageUrl = "/images/flashcards/ohayou.jpg",
                            MeaningEn = "Good morning",
                            MeaningVi = "Chào buổi sáng",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 3,
                            Example = "こんばんは、いい天気ですね。",
                            ExampleEn = "Good evening, the weather is nice, isn’t it?",
                            ExampleVi = "Chào buổi tối, thời tiết thật đẹp nhỉ.",
                            FlashcardCode = "N5-001-003",
                            Front = "こんばんは",
                            Furigana = "こんばんは",
                            ImageUrl = "/images/flashcards/konbanwa.jpg",
                            MeaningEn = "Good evening",
                            MeaningVi = "Chào buổi tối",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 4,
                            Example = "さようなら、またあした。",
                            ExampleEn = "Goodbye, see you tomorrow.",
                            ExampleVi = "Tạm biệt, hẹn gặp lại ngày mai.",
                            FlashcardCode = "N5-001-004",
                            Front = "さようなら",
                            Furigana = "さようなら",
                            ImageUrl = "/images/flashcards/sayounara.jpg",
                            MeaningEn = "Goodbye",
                            MeaningVi = "Tạm biệt",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 5,
                            Example = "プレゼントをありがとう。",
                            ExampleEn = "Thank you for the present.",
                            ExampleVi = "Cảm ơn vì món quà.",
                            FlashcardCode = "N5-001-005",
                            Front = "ありがとう",
                            Furigana = "ありがとう",
                            ImageUrl = "/images/flashcards/arigatou.jpg",
                            MeaningEn = "Thank you",
                            MeaningVi = "Cảm ơn",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 6,
                            Example = "すみません、もういちどおねがいします。",
                            ExampleEn = "Excuse me, please say it once again.",
                            ExampleVi = "Xin lỗi, vui lòng nhắc lại một lần nữa.",
                            FlashcardCode = "N5-001-006",
                            Front = "すみません",
                            Furigana = "すみません",
                            ImageUrl = "/images/flashcards/sumimasen.jpg",
                            MeaningEn = "Excuse me / Sorry",
                            MeaningVi = "Xin lỗi / Làm phiền",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 7,
                            Example = "はい、わかりました。",
                            ExampleEn = "Yes, I understand.",
                            ExampleVi = "Vâng, tôi đã hiểu.",
                            FlashcardCode = "N5-001-007",
                            Front = "はい",
                            Furigana = "はい",
                            ImageUrl = "/images/flashcards/hai.jpg",
                            MeaningEn = "Yes / Correct",
                            MeaningVi = "Vâng / Đúng",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 8,
                            Example = "いいえ、ちがいます。",
                            ExampleEn = "No, that’s not right.",
                            ExampleVi = "Không, không phải vậy.",
                            FlashcardCode = "N5-001-008",
                            Front = "いいえ",
                            Furigana = "いいえ",
                            ImageUrl = "/images/flashcards/iie.jpg",
                            MeaningEn = "No",
                            MeaningVi = "Không",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 9,
                            Example = "はじめまして、やまだです。",
                            ExampleEn = "Nice to meet you, I am Yamada.",
                            ExampleVi = "Rất vui được gặp bạn, tôi là Yamada.",
                            FlashcardCode = "N5-001-009",
                            Front = "はじめまして",
                            Furigana = "はじめまして",
                            ImageUrl = "/images/flashcards/hajimemashite.jpg",
                            MeaningEn = "Nice to meet you",
                            MeaningVi = "Rất vui được gặp bạn",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 10,
                            Example = "おやすみなさい、またあした。",
                            ExampleEn = "Good night, see you tomorrow.",
                            ExampleVi = "Chúc ngủ ngon, hẹn gặp lại ngày mai.",
                            FlashcardCode = "N5-001-010",
                            Front = "おやすみなさい",
                            Furigana = "おやすみなさい",
                            ImageUrl = "/images/flashcards/oyasuminasai.jpg",
                            MeaningEn = "Good night",
                            MeaningVi = "Chúc ngủ ngon",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 11,
                            Example = "りんごをいちつください。",
                            ExampleEn = "Please give me one apple.",
                            ExampleVi = "Xin cho tôi một quả táo.",
                            FlashcardCode = "N5-002-001",
                            Front = "いち",
                            Furigana = "いち",
                            ImageUrl = "/images/flashcards/ichi.jpg",
                            MeaningEn = "One",
                            MeaningVi = "Số một",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 12,
                            Example = "にほんごをべんきょうしています。",
                            ExampleEn = "I am studying Japanese.",
                            ExampleVi = "Tôi đang học tiếng Nhật.",
                            FlashcardCode = "N5-002-002",
                            Front = "に",
                            Furigana = "に",
                            ImageUrl = "/images/flashcards/ni.jpg",
                            MeaningEn = "Two",
                            MeaningVi = "Số hai",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 13,
                            Example = "さんにんのともだちがいます。",
                            ExampleEn = "I have three friends.",
                            ExampleVi = "Tôi có ba người bạn.",
                            FlashcardCode = "N5-002-003",
                            Front = "さん",
                            Furigana = "さん",
                            ImageUrl = "/images/flashcards/san.jpg",
                            MeaningEn = "Three",
                            MeaningVi = "Số ba",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 14,
                            Example = "よんじにあいましょう。",
                            ExampleEn = "Let’s meet at four o’clock.",
                            ExampleVi = "Hãy gặp nhau lúc bốn giờ.",
                            FlashcardCode = "N5-002-004",
                            Front = "よん / し",
                            Furigana = "よん / し",
                            ImageUrl = "/images/flashcards/yon.jpg",
                            MeaningEn = "Four",
                            MeaningVi = "Số bốn",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 15,
                            Example = "ごじにおきます。",
                            ExampleEn = "I wake up at five o’clock.",
                            ExampleVi = "Tôi thức dậy lúc năm giờ.",
                            FlashcardCode = "N5-002-005",
                            Front = "ご",
                            Furigana = "ご",
                            ImageUrl = "/images/flashcards/go.jpg",
                            MeaningEn = "Five",
                            MeaningVi = "Số năm",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 16,
                            Example = "ろっぷんまってください。",
                            ExampleEn = "Please wait for six minutes.",
                            ExampleVi = "Xin hãy chờ sáu phút.",
                            FlashcardCode = "N5-002-006",
                            Front = "ろく",
                            Furigana = "ろく",
                            ImageUrl = "/images/flashcards/roku.jpg",
                            MeaningEn = "Six",
                            MeaningVi = "Số sáu",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 17,
                            Example = "ななじはんにおきます。",
                            ExampleEn = "I get up at half past seven.",
                            ExampleVi = "Tôi dậy lúc bảy giờ rưỡi.",
                            FlashcardCode = "N5-002-007",
                            Front = "しち / なな",
                            Furigana = "しち / なな",
                            ImageUrl = "/images/flashcards/nana.jpg",
                            MeaningEn = "Seven",
                            MeaningVi = "Số bảy",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 18,
                            Example = "はちじにでかけます。",
                            ExampleEn = "I go out at eight o’clock.",
                            ExampleVi = "Tôi ra ngoài lúc tám giờ.",
                            FlashcardCode = "N5-002-008",
                            Front = "はち",
                            Furigana = "はち",
                            ImageUrl = "/images/flashcards/hachi.jpg",
                            MeaningEn = "Eight",
                            MeaningVi = "Số tám",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 19,
                            Example = "きゅうじまでにきてください。",
                            ExampleEn = "Please come by nine o’clock.",
                            ExampleVi = "Hãy đến trước chín giờ.",
                            FlashcardCode = "N5-002-009",
                            Front = "きゅう / く",
                            Furigana = "きゅう / く",
                            ImageUrl = "/images/flashcards/kyuu.jpg",
                            MeaningEn = "Nine",
                            MeaningVi = "Số chín",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 20,
                            Example = "じゅうにんのせいとがいます。",
                            ExampleEn = "There are ten students.",
                            ExampleVi = "Có mười học sinh.",
                            FlashcardCode = "N5-002-010",
                            Front = "じゅう",
                            Furigana = "じゅう",
                            ImageUrl = "/images/flashcards/juu.jpg",
                            MeaningEn = "Ten",
                            MeaningVi = "Số mười",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 21,
                            Example = "わたしのかぞくはごにんです。",
                            ExampleEn = "My family has five people.",
                            ExampleVi = "Gia đình tôi có năm người.",
                            FlashcardCode = "N5-003-001",
                            Front = "かぞく",
                            Furigana = "かぞく",
                            ImageUrl = "/images/flashcards/kazoku.jpg",
                            MeaningEn = "Family",
                            MeaningVi = "Gia đình",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 22,
                            Example = "ちちはぎんこうではたらいています。",
                            ExampleEn = "My father works at a bank.",
                            ExampleVi = "Cha tôi làm việc ở ngân hàng.",
                            FlashcardCode = "N5-003-002",
                            Front = "ちち",
                            Furigana = "ちち",
                            ImageUrl = "/images/flashcards/chichi.jpg",
                            MeaningEn = "Father (talking about one's own)",
                            MeaningVi = "Cha (nói về cha mình)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 23,
                            Example = "はははりょうりがじょうずです。",
                            ExampleEn = "My mother is good at cooking.",
                            ExampleVi = "Mẹ tôi nấu ăn rất giỏi.",
                            FlashcardCode = "N5-003-003",
                            Front = "はは",
                            Furigana = "はは",
                            ImageUrl = "/images/flashcards/haha.jpg",
                            MeaningEn = "Mother (talking about one's own)",
                            MeaningVi = "Mẹ (nói về mẹ mình)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 24,
                            Example = "おとうさんはどこですか。",
                            ExampleEn = "Where is your father?",
                            ExampleVi = "Bố bạn ở đâu?",
                            FlashcardCode = "N5-003-004",
                            Front = "おとうさん",
                            Furigana = "おとうさん",
                            ImageUrl = "/images/flashcards/otousan.jpg",
                            MeaningEn = "Father (polite)",
                            MeaningVi = "Bố (cách gọi lịch sự)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 25,
                            Example = "おかあさんはげんきですか。",
                            ExampleEn = "How is your mother?",
                            ExampleVi = "Mẹ bạn có khỏe không?",
                            FlashcardCode = "N5-003-005",
                            Front = "おかあさん",
                            Furigana = "おかあさん",
                            ImageUrl = "/images/flashcards/okaasan.jpg",
                            MeaningEn = "Mother (polite)",
                            MeaningVi = "Mẹ (cách gọi lịch sự)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 26,
                            Example = "あにはだいがくせいです。",
                            ExampleEn = "My older brother is a university student.",
                            ExampleVi = "Anh trai tôi là sinh viên đại học.",
                            FlashcardCode = "N5-003-006",
                            Front = "あに",
                            Furigana = "あに",
                            ImageUrl = "/images/flashcards/ani.jpg",
                            MeaningEn = "Older brother (talking about one's own)",
                            MeaningVi = "Anh trai (nói về anh mình)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 27,
                            Example = "あねはせんせいです。",
                            ExampleEn = "My older sister is a teacher.",
                            ExampleVi = "Chị gái tôi là giáo viên.",
                            FlashcardCode = "N5-003-007",
                            Front = "あね",
                            Furigana = "あね",
                            ImageUrl = "/images/flashcards/ane.jpg",
                            MeaningEn = "Older sister (talking about one's own)",
                            MeaningVi = "Chị gái (nói về chị mình)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 28,
                            Example = "おにいさんはなんさいですか。",
                            ExampleEn = "How old is your older brother?",
                            ExampleVi = "Anh trai bạn bao nhiêu tuổi?",
                            FlashcardCode = "N5-003-008",
                            Front = "おにいさん",
                            Furigana = "おにいさん",
                            ImageUrl = "/images/flashcards/oniisan.jpg",
                            MeaningEn = "Older brother (polite)",
                            MeaningVi = "Anh trai (lịch sự)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 29,
                            Example = "おねえさんはべんきょうしていますか。",
                            ExampleEn = "Is your older sister studying?",
                            ExampleVi = "Chị gái bạn có đang học không?",
                            FlashcardCode = "N5-003-009",
                            Front = "おねえさん",
                            Furigana = "おねえさん",
                            ImageUrl = "/images/flashcards/oneesan.jpg",
                            MeaningEn = "Older sister (polite)",
                            MeaningVi = "Chị gái (lịch sự)",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 30,
                            Example = "きょうだいはなんにんいますか。",
                            ExampleEn = "How many siblings do you have?",
                            ExampleVi = "Bạn có mấy anh chị em?",
                            FlashcardCode = "N5-003-010",
                            Front = "きょうだい",
                            Furigana = "きょうだい",
                            ImageUrl = "/images/flashcards/kyoudai.jpg",
                            MeaningEn = "Siblings",
                            MeaningVi = "Anh chị em",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 31,
                            Example = "がっこうへいきます。",
                            ExampleEn = "I go to school.",
                            ExampleVi = "Tôi đi đến trường.",
                            FlashcardCode = "N5-004-001",
                            Front = "がっこう",
                            Furigana = "がっこう",
                            ImageUrl = "/images/flashcards/gakkou.jpg",
                            MeaningEn = "School",
                            MeaningVi = "Trường học",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 32,
                            Example = "せんせいはにほんじんです。",
                            ExampleEn = "The teacher is Japanese.",
                            ExampleVi = "Giáo viên là người Nhật.",
                            FlashcardCode = "N5-004-002",
                            Front = "せんせい",
                            Furigana = "せんせい",
                            ImageUrl = "/images/flashcards/sensei.jpg",
                            MeaningEn = "Teacher",
                            MeaningVi = "Giáo viên",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 33,
                            Example = "わたしはがくせいです。",
                            ExampleEn = "I am a student.",
                            ExampleVi = "Tôi là sinh viên.",
                            FlashcardCode = "N5-004-003",
                            Front = "がくせい",
                            Furigana = "がくせい",
                            ImageUrl = "/images/flashcards/gakusei.jpg",
                            MeaningEn = "Student",
                            MeaningVi = "Học sinh / Sinh viên",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 34,
                            Example = "きょうしつはにかいにあります。",
                            ExampleEn = "The classroom is on the second floor.",
                            ExampleVi = "Phòng học ở tầng hai.",
                            FlashcardCode = "N5-004-004",
                            Front = "きょうしつ",
                            Furigana = "きょうしつ",
                            ImageUrl = "/images/flashcards/kyoushitsu.jpg",
                            MeaningEn = "Classroom",
                            MeaningVi = "Phòng học",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 35,
                            Example = "ほんをよみます。",
                            ExampleEn = "I read books.",
                            ExampleVi = "Tôi đọc sách.",
                            FlashcardCode = "N5-004-005",
                            Front = "ほん",
                            Furigana = "ほん",
                            ImageUrl = "/images/flashcards/hon.jpg",
                            MeaningEn = "Book",
                            MeaningVi = "Sách",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 36,
                            Example = "えんぴつでかきます。",
                            ExampleEn = "I write with a pencil.",
                            ExampleVi = "Tôi viết bằng bút chì.",
                            FlashcardCode = "N5-004-006",
                            Front = "えんぴつ",
                            Furigana = "えんぴつ",
                            ImageUrl = "/images/flashcards/enpitsu.jpg",
                            MeaningEn = "Pencil",
                            MeaningVi = "Bút chì",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 37,
                            Example = "じしょをつかいます。",
                            ExampleEn = "I use a dictionary.",
                            ExampleVi = "Tôi dùng từ điển.",
                            FlashcardCode = "N5-004-007",
                            Front = "じしょ",
                            Furigana = "じしょ",
                            ImageUrl = "/images/flashcards/jisho.jpg",
                            MeaningEn = "Dictionary",
                            MeaningVi = "Từ điển",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 38,
                            Example = "らいしゅうしけんがあります。",
                            ExampleEn = "There is an exam next week.",
                            ExampleVi = "Tuần sau có kỳ thi.",
                            FlashcardCode = "N5-004-008",
                            Front = "しけん",
                            Furigana = "しけん",
                            ImageUrl = "/images/flashcards/shiken.jpg",
                            MeaningEn = "Exam / Test",
                            MeaningVi = "Kỳ thi",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 39,
                            Example = "まいにちべんきょうします。",
                            ExampleEn = "I study every day.",
                            ExampleVi = "Tôi học mỗi ngày.",
                            FlashcardCode = "N5-004-009",
                            Front = "べんきょう",
                            Furigana = "べんきょう",
                            ImageUrl = "/images/flashcards/benkyou.jpg",
                            MeaningEn = "Study / To study",
                            MeaningVi = "Học tập",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 40,
                            Example = "やすみじかんにともだちとあそびます。",
                            ExampleEn = "I play with friends during break time.",
                            ExampleVi = "Trong giờ nghỉ tôi chơi với bạn.",
                            FlashcardCode = "N5-004-010",
                            Front = "やすみじかん",
                            Furigana = "やすみじかん",
                            ImageUrl = "/images/flashcards/yasumijikan.jpg",
                            MeaningEn = "Break time / Recess",
                            MeaningVi = "Giờ nghỉ",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 41,
                            Example = "みせでくだものをかいます。",
                            ExampleEn = "I buy fruit at the shop.",
                            ExampleVi = "Tôi mua hoa quả ở cửa hàng.",
                            FlashcardCode = "N5-005-001",
                            Front = "みせ",
                            Furigana = "みせ",
                            ImageUrl = "/images/flashcards/mise.jpg",
                            MeaningEn = "Shop / Store",
                            MeaningVi = "Cửa hàng",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 42,
                            Example = "かいものにいきます。",
                            ExampleEn = "I go shopping.",
                            ExampleVi = "Tôi đi mua sắm.",
                            FlashcardCode = "N5-005-002",
                            Front = "かいもの",
                            Furigana = "かいもの",
                            ImageUrl = "/images/flashcards/kaimono.jpg",
                            MeaningEn = "Shopping",
                            MeaningVi = "Mua sắm",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 43,
                            Example = "ほんをかいました。",
                            ExampleEn = "I bought a book.",
                            ExampleVi = "Tôi đã mua một quyển sách.",
                            FlashcardCode = "N5-005-003",
                            Front = "かう",
                            Furigana = "かう",
                            ImageUrl = "/images/flashcards/kau.jpg",
                            MeaningEn = "To buy",
                            MeaningVi = "Mua",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 44,
                            Example = "このみせはやさいをうっています。",
                            ExampleEn = "This shop sells vegetables.",
                            ExampleVi = "Cửa hàng này bán rau.",
                            FlashcardCode = "N5-005-004",
                            Front = "うる",
                            Furigana = "うる",
                            ImageUrl = "/images/flashcards/uru.jpg",
                            MeaningEn = "To sell",
                            MeaningVi = "Bán",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 45,
                            Example = "このシャツはやすいです。",
                            ExampleEn = "This shirt is cheap.",
                            ExampleVi = "Chiếc áo này rẻ.",
                            FlashcardCode = "N5-005-005",
                            Front = "やすい",
                            Furigana = "やすい",
                            ImageUrl = "/images/flashcards/yasui.jpg",
                            MeaningEn = "Cheap / Inexpensive",
                            MeaningVi = "Rẻ",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 46,
                            Example = "このくつはたかいです。",
                            ExampleEn = "These shoes are expensive.",
                            ExampleVi = "Đôi giày này đắt.",
                            FlashcardCode = "N5-005-006",
                            Front = "たかい",
                            Furigana = "たかい",
                            ImageUrl = "/images/flashcards/takai.jpg",
                            MeaningEn = "Expensive / High",
                            MeaningVi = "Đắt / Cao",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 47,
                            Example = "あたらしいかばんをかいました。",
                            ExampleEn = "I bought a new bag.",
                            ExampleVi = "Tôi đã mua một chiếc túi mới.",
                            FlashcardCode = "N5-005-007",
                            Front = "かばん",
                            Furigana = "かばん",
                            ImageUrl = "/images/flashcards/kaban.jpg",
                            MeaningEn = "Bag / Backpack",
                            MeaningVi = "Cặp sách / Túi",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 48,
                            Example = "さいふをなくしました。",
                            ExampleEn = "I lost my wallet.",
                            ExampleVi = "Tôi làm mất ví.",
                            FlashcardCode = "N5-005-008",
                            Front = "さいふ",
                            Furigana = "さいふ",
                            ImageUrl = "/images/flashcards/saifu.jpg",
                            MeaningEn = "Wallet",
                            MeaningVi = "Ví tiền",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 49,
                            Example = "シャツをきます。",
                            ExampleEn = "I wear a shirt.",
                            ExampleVi = "Tôi mặc áo sơ mi.",
                            FlashcardCode = "N5-005-009",
                            Front = "きる",
                            Furigana = "きる",
                            ImageUrl = "/images/flashcards/kiru.jpg",
                            MeaningEn = "To wear/put on (clothes, upper body)",
                            MeaningVi = "Mặc (quần áo)",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 50,
                            Example = "くつをはきます。",
                            ExampleEn = "I put on shoes.",
                            ExampleVi = "Tôi mang giày.",
                            FlashcardCode = "N5-005-010",
                            Front = "はく",
                            Furigana = "はく",
                            ImageUrl = "/images/flashcards/haku.jpg",
                            MeaningEn = "To wear/put on (shoes, pants, skirt)",
                            MeaningVi = "Mang (giày, quần)",
                            TopicId = 5
                        });
                });

            modelBuilder.Entity("Last02.Data.Entities.LocalizedMessage", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Code", "LanguageCode");

                    b.ToTable("LocalizedMessages");
                });

            modelBuilder.Entity("Last02.Data.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MemberLastActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimesIsLogoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Last02.Data.Entities.MemberCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("Progress")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberCourses");
                });

            modelBuilder.Entity("Last02.Data.Entities.MemberFlashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlashcardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RememberCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberFlashcards");
                });

            modelBuilder.Entity("Last02.Data.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HexColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TopicCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Description = "Học các câu chào hỏi và giao tiếp cơ bản trong tiếng Nhật N5.",
                            HexColorCode = "#FFB74D",
                            IsFree = true,
                            Title = "Chào hỏi cơ bản",
                            TopicCode = "N5-001"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Description = "Học cách đếm số, nói giờ, ngày tháng trong tiếng Nhật N5.",
                            HexColorCode = "#4DB6AC",
                            IsFree = true,
                            Title = "Số đếm & Thời gian",
                            TopicCode = "N5-002"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            Description = "Từ vựng và mẫu câu liên quan đến gia đình trong tiếng Nhật N5.",
                            HexColorCode = "#64B5F6",
                            IsFree = false,
                            Title = "Gia đình",
                            TopicCode = "N5-003"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            Description = "Từ vựng và mẫu câu sử dụng trong môi trường học tập.",
                            HexColorCode = "#BA68C8",
                            IsFree = false,
                            Title = "Trường học",
                            TopicCode = "N5-004"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 1,
                            Description = "Từ vựng và mẫu câu giao tiếp khi đi mua sắm.",
                            HexColorCode = "#E57373",
                            IsFree = false,
                            Title = "Mua sắm",
                            TopicCode = "N5-005"
                        });
                });

            modelBuilder.Entity("Last02.Data.Entities.UserDeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDeviceTokens");
                });

            modelBuilder.Entity("Last02.Data.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastForgotPasswordRequestAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialProviderToken")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TemporaryPasswordExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("TemporaryPasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Last02.Data.Entities.Audio", b =>
                {
                    b.HasOne("Last02.Data.Entities.Course", "Course")
                        .WithMany("Audios")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Last02.Data.Entities.Flashcard", b =>
                {
                    b.HasOne("Last02.Data.Entities.Topic", "Topic")
                        .WithMany("Flashcards")
                        .HasForeignKey("TopicId");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Last02.Data.Entities.Member", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Last02.Data.Entities.Users", "User")
                        .WithOne("Member")
                        .HasForeignKey("Last02.Data.Entities.Member", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Last02.Data.Entities.MemberCourse", b =>
                {
                    b.HasOne("Last02.Data.Entities.Course", "Course")
                        .WithMany("MemberCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Last02.Data.Entities.Member", "Member")
                        .WithMany("MemberCourses")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Last02.Data.Entities.MemberFlashcard", b =>
                {
                    b.HasOne("Last02.Data.Entities.Flashcard", "Flashcard")
                        .WithMany()
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Last02.Data.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Last02.Data.Entities.Topic", b =>
                {
                    b.HasOne("Last02.Data.Entities.Course", "Course")
                        .WithMany("Topics")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Last02.Data.Entities.UserDeviceToken", b =>
                {
                    b.HasOne("Last02.Data.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Last02.Data.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Last02.Data.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Last02.Data.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Last02.Data.Entities.Users", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UsersId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Last02.Data.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Last02.Data.Entities.Course", b =>
                {
                    b.Navigation("Audios");

                    b.Navigation("MemberCourses");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Last02.Data.Entities.Member", b =>
                {
                    b.Navigation("MemberCourses");
                });

            modelBuilder.Entity("Last02.Data.Entities.Topic", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("Last02.Data.Entities.Users", b =>
                {
                    b.Navigation("Member");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
